server {
    listen 80;
    listen [::]:80;

    server_name panel.kwl 192.168.1.51;

    root /var/www/kwl/backend/public;
    index index.php index.html;

    location /frontend/ {
        alias /var/www/kwl/frontend/;
        index index.html;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location ~ /\. {
        deny all;
    }
}
